# -*- coding: utf-8 -*-
"""without flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0X_o4FsLrto1Mq6kUPH__9OJxMlQPt2

## <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">1. Import Libraries</div>
"""


# Commented out IPython magic to ensure Python compatibility.
# data
import pandas as pd
import numpy as np


# visualization
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno # مكتبة متخصصة في تصوير القيم المفقودة

import plotly.express as px #لعمل رسومات Interactive بسرعة بسطر واحد.

import plotly.figure_factory as ff # Figure Factory لرسومات متخصصة مش متاحة مباشرة في px >> زي توزيعات و الكثافه مثلا
import plotly.graph_objects as go

from wordcloud import WordCloud # نستخدمها لإعطاء لمحة سريعة عن الكلمات الأكثر شيوعًا في نصوص

# styling
# %matplotlib inline
sns.set_style('darkgrid')
mpl.rcParams['font.size'] = 14
mpl.rcParams['figure.facecolor'] = '#00000000'
mpl.rcParams['font.size'] = 14
mpl.rcParams['figure.facecolor'] = '#00000000'

import os
from wordcloud import WordCloud

import warnings
warnings.filterwarnings("ignore")

"""## <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">2. Read and Explain Dataset</div>"""

#Read data
data_original =  pd.read_csv("C:\\Users\\Mosta\\OneDrive\\Documents\\eslam\\credit_risk_dataset.csv")
data = pd.read_csv("C:\\Users\\Mosta\\OneDrive\\Documents\\eslam\\credit_risk_dataset.csv")

data

data.columns

"""### 🧾 Column Descriptions

- **person_age** >>> عمر المتقدِّم بالسنوات وقت التقديم  
- **person_income** >>> الدخل السنوي الإجمالي للمتقدِّم  
- **person_home_ownership** >>> حالة سكن المتقدِّم (Own/Rent/Mortgage/Other)  
- **person_emp_length** >>> مدة الخبرة العملية بالسنوات  
- **loan_intent** >>> الغرض من القرض (مثلًا: تعليم، سيارة، أعمال...)  
- **loan_grade** >>> درجة/تصنيف جودة القرض حسب الجهة المموِّلة (A–G عادةً)  
- **loan_amnt** >>> قيمة القرض المطلوبة أو المصروفة  
- **loan_int_rate** >>> معدل الفائدة السنوي للقرض (نسبة مئوية)  
- **loan_status** >>> حالة الهدف (سداد ناجح أم تعثّر عن السداد)  
- **loan_percent_income** >>> نسبة قيمة القرض إلى دخل المتقدِّم (loan_amnt / income)  
- **cb_person_default_on_file** >>> وجود تعثّر سابق في السجل الائتماني (Y/N)  
- **cb_person_cred_hist_length** >>> طول السجل الائتماني للمتقدِّم (بالسنوات)
**bold text**

## <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">3. EDA</div>
"""



data.head()

data.tail()

data.describe()

data.info()

data.isnull().sum()

data.nunique()

data.loan_status.value_counts()

data.duplicated().sum()

#  الارتباط فقط بين الأعمدة الرقمية
correlation_table = data.select_dtypes(include=[np.number]).corr()
# اختار الأعمدة اللي نوعها رقمي فقط

print("Correlation matrix:\n")
print(correlation_table)

# person_age ↔ cb_person_cred_hist_length → 0.86   علاقة طردية قوية جدًا
# loan_amnt ↔ loan_percent_income → 0.57        علاقة طردية متوسطة
# loan_status ↔ loan_int_rate → 0.34              علاقة طردية متوسطة (الفائدة العالية اقرب للتعثر)
# loan_status ↔ loan_percent_income → 0.38         علاقة متوسطة (نسبة القرض للدخل تؤثر على السداد)
# person_income ↔ loan_amnt → 0.27                 علاقة ضعيفة

"""## Univarient Analysis"""

#MAX AND MIN AGE
#تحليل عمود person_age لمعرفة:
# أكبر وأصغر عمر موجود في الداتا.

max_ = data['person_age'].max()
min_ = data['person_age'].min()
print(f"maximum Age {max_}")
print(f"minimum Age {min_}")
print("_"*70)
# توزيع الناس على فئات عمرية (من 0–18، 19–26، 27–36 وهكذا).

mx = int(data['person_age'].max())
bins = [0, 18, 26, 36, 46, 56, 66, mx]
labels = ["0-18", "19-26", "27-36", "37-46", "47-56", "57-66", f"67-{mx}"]

counts = pd.cut(data['person_age'],bins=bins,labels=labels,right=True,include_lowest=True).value_counts(sort=False)
print(counts)

 # وجود عمر 144 سنة غير واقعي

s = data['person_age']
counts = pd.cut(s, bins=bins, labels=labels, include_lowest=True).value_counts(sort=False)
counts.plot(kind='bar'); plt.title('person_age (buckets)'); plt.ylabel('count'); plt.tight_layout(); plt.show()

#max and min income
max_ = data['person_income'].max()
min_ = data['person_income'].min()
print(f"maximum Income {max_}")
print(f"minimum Income {min_}")

 # np.inf >>> "Infinity" = عدد لا نهائي (∞) >>
 # كحدّ أعلى مفتوح للفئة الأخيرة
# عدّ أصحاب الدخل صفر + (اختياري) المفقودات
inc_bins = [1, 4000, 10000, 25000, 50000, 75000, 100000, 150000, 250000,
            500000, 1000000, 2000000, 5000000, np.inf]

inc_counts = pd.cut(
    data.loc[data['person_income'] > 0, 'person_income'],
    bins=inc_bins,
    include_lowest=True
).value_counts(sort=False)

print(f"Income == 0: {(data['person_income'] == 0).sum()}")
for r, n in inc_counts.items():
    print(f"Income {r}: {n}")

#min and max loan amount
print(f"maximum Loan Amount {data['loan_amnt'].max()}")
print(f"minimum Loan Amount {data['loan_amnt'].min()}")

loan_bins = [1, 1000, 3000, 5000, 10000, 15000, 20000, 25000, 30000, 35000]
loan_counts = pd.cut(data['loan_amnt'],bins=loan_bins,include_lowest=True,right=True).value_counts(sort=False)
for r, n in loan_counts.items():
    print(f"Loan Amount {r}: Number of people {n}")

bins = [3000,5000,10000,15000,20000,25000,30000,35000]
vals, edges = np.histogram(data['loan_amnt'], bins=bins)
centers = 0.5*(edges[1:]+edges[:-1])

plt.bar(centers, vals, width=np.diff(edges), align='center')
plt.xticks(edges, [f"{int(b/1000)}k" for b in edges])
plt.xlabel('loan amount'); plt.ylabel('count'); plt.title('Loan amount (histogram)')
plt.tight_layout(); plt.show()

# نوع السكن لكل عميل
# RENT → ساكن إيجار
# OWN → عنده بيت ملك
# MORTGAGE → شاري بيت بقرض (تمويل عقاري)
# OTHER → نوع سكن آخر

level_counts = data['person_home_ownership'].value_counts()
fig = px.bar(x=level_counts.index, y=level_counts.values,
             title='person_home_ownership', labels={'x':'category','y':'count'})
fig.update_layout(xaxis_tickangle=-30)
fig.show()

fig=px.histogram(data, x = 'loan_intent',histnorm = 'percent', text_auto = '.2f',template = 'presentation', title = 'loan intent',color_discrete_sequence=px.colors.sequential.Mint)
fig.update_layout()
fig.show()

#  أعمدة توضح توزيع أغراض القروض كنِسَب.

"""# <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">4. Dealing with Outliers</div>"""

data.isnull().sum()

data['person_emp_length'].fillna(data['person_emp_length'].mean(), inplace=True)
data['loan_int_rate'].fillna(data['loan_int_rate'].mean(), inplace=True)

data.isnull().sum()

data['loan_status'].value_counts()

data.describe()

# اعتبر القيم الشاذة NaN
data.loc[(data['person_age'] < 18) | (data['person_age'] > 100), 'person_age'] = np.nan
data.loc[(data['person_emp_length'] < 0) | (data['person_emp_length'] > 60), 'person_emp_length'] = np.nan

# تعويض القيم المفقودة بالمتوسط
data['person_age'].fillna(data['person_age'].mean(), inplace=True)
data['person_emp_length'].fillna(data['person_emp_length'].mean(), inplace=True)

# import matplotlib.pyplot as plt
# verti = data['person_age'].value_counts().values
# hori = data['person_age'].value_counts().index
# fig = plt.figure(figsize = (15, 5))
# plt.bar(hori, verti)
# # after 80 it is rare

"""# <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">5. Feature Engineering</div>"""

data['age_group'] = pd.cut(data['person_age'],
                           bins=[20, 26, 36, 46, 56, 66],
                           labels=['20-25', '26-35', '36-45', '46-55', '56-65'])
# لتسهيل القراءة :
# كوّن عمود جديد اسمه age_group
# عن طريق تقسيم عمر الشخص (person_age) إلى فئات عمرية محددة

data['age_group'].dtype

data.head()

"""## **Income Group**"""

data['income_group'] = pd.cut(data['person_income'],
                              bins=[0, 25000, 50000, 75000, 100000, float('inf')],
                              labels=['low', 'low-middle', 'middle', 'high-middle', 'high'])

# لتسهيل القراءة ايضا
# كوّن عمود جديد اسمه income_group
# عن طريق تقسيم مرتب الشخص (person_income) إلى فئات مالية محددة

data.head()

"""## **Loan Amount**"""

data['loan_amount_group'] = pd.cut(data['loan_amnt'],
                                   bins=[0, 5000, 10000, 15000, float('inf')],
                                   labels=['small', 'medium', 'large', 'very large'])

# كون عمود جديد لتصنيف القروض

data['loan_amount_group']

data.head()

# خلق أعمدة جديدة تمثل نِسَب بين عمودين علشان >> تطبيع المقاييس بدل ما تبص للمبلغ والدخل منفصلين >> التقاط علاقات غير خطية
# ربط بين مقادير مهمة بدل ما تبص لكل عمود لوحده

# نسبة القرض إلى الدخل. كل ما تكبر النسبة، العبء النسبي للقرض أعلى >> غالبًا مخاطرة أعلى بالتعثّر.
# Create loan-to-income ratio
data['loan_to_income_ratio'] = data['loan_amnt'] / data['person_income']

# طول الخبرة لكل وحدة من مبلغ القرض. خبرة أكبر مقابل قرض أصغر تعطي قيمة أعلى (قد تعني استقرار نسبي)
# Create loan-to-employment length ratio
data['loan_to_emp_length_ratio'] =  data['person_emp_length']/ data['loan_amnt']

# سعر الفائدة لكل وحدة من مبلغ القرض
# Create interest rate-to-loan amount ratio
data['int_rate_to_loan_amt_ratio'] = data['loan_int_rate'] / data['loan_amnt']

raw_data = data.copy()

col_list = ['person_age',   # Features + Target
 'person_income',
 'person_home_ownership',
 'person_emp_length',
 'loan_intent',
 'loan_grade',
 'loan_amnt',
 'loan_int_rate',
 'loan_status',
 'loan_percent_income',
 'cb_person_default_on_file',
 'cb_person_cred_hist_length',
'age_group','income_group','loan_amount_group']

drop_colums = [] # قائمة الأعمدة المراد حذفها ، بنحط فيها أي أعمدة هتستبعدها
scale_cols = ['person_income','person_age','person_emp_length', 'loan_amnt','loan_int_rate','cb_person_cred_hist_length','loan_percent_income','loan_to_income_ratio', 'loan_to_emp_length_ratio',
       'int_rate_to_loan_amt_ratio']
# الأعمدة العددية اللي هتتعملّها >>> Scaling (Standard/MinMa) >>> زي person_income, loan_amnt

ohe_colums = ['cb_person_default_on_file','loan_grade', 'person_home_ownership','loan_intent','income_group','age_group','loan_amount_group']
#الأعمدة اللي هتتعملّها >> One-Hot Encoding >> زي loan_grade, person_home_ownership >> وكمان الاعمدة الجديده زي income_group, age_group, loan_amount_group

le_colums = [] # احتياطي لو احتجت اعمل Label Encoding
# حاليا مفيش

data = data.drop(drop_colums, axis=1)

data.columns

"""# <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">6. Data Preprocessing</div>

"""

# my target is "loan_status"
#

X = data.drop(['loan_status'], axis=1) # axis=1 يعني على الأعمدة
Y = data['loan_status']

# splitting

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=12)

print(x_train.shape,x_test.shape)

x_train.reset_index(inplace = True)
x_test.reset_index(inplace = True)

x_train.columns

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(x_train[ohe_colums])

ohe.categories_

merge_ohe_col = np.concatenate((ohe.categories_[0],
                ohe.categories_[1],
                ohe.categories_[2],
                ohe.categories_[3],
                ohe.categories_[4],
                ohe.categories_[5],
                ohe.categories_[6],))

#  تجميع كل الفئات الأصلية التي تعلّمها الـ
# OneHotEncoder
# من أول 7 أعمدة فئوية في مصفوفة واحدة.

merge_ohe_col

# تجميع الوان هوت انكودر اعمدة التدريب
ohe_data = pd.DataFrame(ohe.transform(x_train[ohe_colums]).toarray(), columns=merge_ohe_col)
# ohe.transform >> يحوّلها لمصفوفة One-Hot (0/1) بناءً على الفئات التي تعلّمها في fit
# toarray() >> حوّل الناتج من مصفوفة sparse matrix متناثره او مش متجمعه >>>
# الي  pd.DataFrame

# تجميع الوان هوت انكودر اعمدة التيست
ohe_data2 = pd.DataFrame(ohe.transform(x_test[ohe_colums]).toarray(),columns=merge_ohe_col)

X_new = pd.concat([ohe_data, x_train], axis=1)
X_new = X_new.drop(ohe_colums, axis=1)
# ضم الأعمدة الـ One-Hot الجديده
# مع الداتا الأصلية

X_new_test = pd.concat([ohe_data2, x_test], axis=1) # نفس الكلام للتيست
X_new_test = X_new_test.drop(ohe_colums, axis=1)

X_new.head()
X_new.shape

X_new_test.head()

# اختيار السكّيلر المناسب لكل نمط توزيع.

from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler
# مناسب لو مفيش آوتلايرز قوية >> MinMaxScaler >>> يعيد قياس القيم إلى مجال ثابت (افتراضيًا [0, 1]).
# StandardScaler >> يركز البيانات حول المتوسط ويجعل الانحراف المعياري ≈ 1
# RobustScaler >> يعتمد على الميديان و IQR >> فا بيتعامل احسن مع الاوتلايرز

scale_cols = ['person_income','person_age','person_emp_length', 'loan_amnt','loan_int_rate','cb_person_cred_hist_length','loan_percent_income', 'loan_to_emp_length_ratio',
       'int_rate_to_loan_amt_ratio']
       # قائمة عامة بالأعمدة المراد عمل سكيلينج لها

uniform_col= []

normal_col = ['person_income','person_age','person_emp_length', 'loan_amnt','loan_int_rate','cb_person_cred_hist_length','loan_percent_income', 'loan_to_emp_length_ratio',
       'int_rate_to_loan_amt_ratio']

bimodal_col = [] # ليست للأعمدة اللي توزيعها فيه آوتلايرز قوية هتستخدمها بعدين


scaler_uniform = MinMaxScaler()
#X_new.loc[:,uniform_col] = scaler_uniform.fit_transform(X_new.loc[:,uniform_col])
#X_new_test.loc[:,uniform_col] = scaler_uniform.transform(X_new_test.loc[:,uniform_col])

scaler_normal = StandardScaler()
X_new.loc[:,normal_col] = scaler_normal.fit_transform(X_new.loc[:,normal_col])
X_new_test.loc[:,normal_col] = scaler_normal.transform(X_new_test.loc[:,normal_col])

scaler_bimodal = RobustScaler()
#X_new.loc[:,bimodal_col] = scaler_bimodal.fit_transform(X_new.loc[:,bimodal_col])
#X_new_test.loc[:,bimodal_col] = scaler_bimodal.transform(X_new_test.loc[:,bimodal_col])

X_new_test.head()

"""# <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">7. ML Classification Models</div>

"""


# 1) Classification Models

from sklearn.svm import SVC  # يفصل الحدود بأكبر هامش و كويس اوي على الداتا اللي ليها فيتشرز صغيرة/متوسطة

from sklearn.naive_bayes import MultinomialNB  # مصنّف بايز مناسب لبيانات عدّ/Counts غير سالبة (نصوص/TF)

from sklearn.tree import DecisionTreeClassifier  # شجرة قرار للتصنيف؛ تلتقط اللاخطّية والتفاعلات ببساطة

from sklearn.neighbors import KNeighborsClassifier  # مصنّف أقرب الجيران؛ يحتاج Scaling وغالي حسابيًا وقت التست

from sklearn.ensemble import RandomForestClassifier  # غابة عشوائية قوية وثابتة؛ تقليل تباين + أهمية خصائص

from sklearn.ensemble import AdaBoostClassifier  # مفيد على داتا نظيفة وحدود واضحة (Boosting بمتعلمين ضعفاء)

from sklearn.ensemble import BaggingClassifier  # مجمّع Bagging للتصنيف يقلّل التباين عبر Bootstrap

from sklearn.ensemble import ExtraTreesClassifier  # أشجار شديدة العشوائية؛ سريعة وأحيانًا أقل تباين

from sklearn.ensemble import GradientBoostingClassifier  # Gradient Boosting للتصنيف (GBDT سكِتليرن)

from xgboost import XGBClassifier  # مصنّف XGBoost قوي على الجداول ويدعم عدم توازن بالفئة

from sklearn.linear_model import LogisticRegression  # مصنّف لوجستي خطّي سريع ويطلع احتمالات واضحة

from catboost import CatBoostClassifier  # ممتاز مع (Categoricals) مباشرةً

import lightgbm as lgb
from lightgbm import LGBMClassifier  # LightGBM للتصنيف سريع وفعّال على الداتا الجدولية

# 2) Regression Models
# from sklearn.linear_model import LinearRegression  # انحدار خطّي لمهام Regression (مش تصنيف)
# from lightgbm import LGBMRegressor                 # LightGBM للانحدار (Regression)

# 3) أدوات القياس
from sklearn.metrics import make_scorer  # بناء Scorer مخصّص لاستخدامه في Grid/CV

# from sklearn.metrics import mean_squared_error as MSE  # مقياس للـ Regression (مش للتصنيف)
# from sklearn.metrics import mean_absolute_error  # مقياس للـ Regression (مش للتصنيف)

# 4) ضبط الهايبر بارامترز (Optimization)
from hyperopt import hp, fmin, tpe  # أفضل قيم للسوبر-بارامترز (زي n_estimators, max_depth, learning_rate في XGBoost). بدل ما نجرّب يدوي
from bayes_opt import BayesianOptimization  # لضبط هايبر باراميترز نماذج مثل LightGBM/XGBoost/CatBoost بسرعة وكفاءة.

# 5) تقسيمات وتقييم بالنمط المتقاطع (CV)
from sklearn.model_selection import GridSearchCV, StratifiedKFold
# GridSearchCV: بحث شبكي منظّم على قيم محدّدة. >>>>> StratifiedKFold: تقسيم K-Fold يحافظ على نسبة الفئات مهم جدًا مع عدم التوازن

from sklearn.model_selection import KFold, cross_val_score  # KFold بدون حفظ نسب الفئات + حساب نتائج CV بسرعة

#####################

from sklearn.linear_model import LinearRegression
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error as MSE

svc = SVC()
knc = KNeighborsClassifier() #algorithm='ball_tree', leaf_size=10, n_neighbors=18, p=1, weights='distance'
mnb = MultinomialNB()
dtc = DecisionTreeClassifier()
lrc = LogisticRegression()
rfc = RandomForestClassifier()
abc = AdaBoostClassifier()
bc = BaggingClassifier()
etc = ExtraTreesClassifier()
gbdt = GradientBoostingClassifier()
xgb = XGBClassifier()
cat = CatBoostClassifier(verbose=0)
lgb = lgb.LGBMClassifier()

svc = SVC()
knc = KNeighborsClassifier()  # algorithm='ball_tree', leaf_size=10, n_neighbors=18, p=1, weights='distance'

mnb = MultinomialNB()  # مصنّف بايز; يتوقّع مدخلات غير سالبة (counts/TF)، مش مقيّسة بقيم سالبة

dtc = DecisionTreeClassifier()  # شجرة قرار للتصنيف

lrc = LogisticRegression()
rfc = RandomForestClassifier()
abc = AdaBoostClassifier()
bc  = BaggingClassifier()
etc = ExtraTreesClassifier()  # أشجار شديدة العشوائية؛ سريعة غالبًا

gbdt = GradientBoostingClassifier()
xgb = XGBClassifier()
cat = CatBoostClassifier()
from lightgbm import LGBMClassifier
lgb_clf = LGBMClassifier()  # تبني النموذج على مراحل و بتعتمد على أشجار القرار بهدف التصنيف بسرعة وكفاءة عالية

# جمع الموديلات في قاموس عشان نشغّل، نقارن، وندير نتائج موديلات كتير

clf = {
    'RF': rfc,
    'LR': lrc,
    'DT': dtc,
    'KN' : knc,
    'xgb':xgb,
    'cat':cat,
}

# clfs = {
#     'SVC' : svc,
#     'KN' : knc,
#     'NB': mnb,
#     'DT': dtc,
#     'LR': lrc,
#     'RF': rfc,
#     'AdaBoost': abc,
#     'BgC': bc,
#     'ETC': etc,
#     'GBDT':gbdt,
#     'xgb':xgb
# }

from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)  # تدريب الموديل على بيانات التدريب
    y_pred = clf.predict(X_test) # توليد التوقعات

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    # حساب CM to get >>> TN and FP
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()  # ravel() >>> يفترض مصفوفة 2×2
    specificity = tn / (tn + fp)
    # نسبة السالب الحقيقي اللي النموذج اكتشفه صح من كل السوالب الفعلية.

    return accuracy, precision, recall, specificity
# -_- -_- -_- -_- -_- -_- -_- -_- -_- -_- -_- #

# Precision = TP / (TP + FP)
# Recall  = TP / (TP + FN)

# -_- -_- -_- -_- -_- -_- -_- -_- -_- -_- -_- #

# Usage
# accuracy, precision, recall, specificity = train_classifier(clf, x_train, y_train, X_test, y_test)
# print("Accuracy:", accuracy)
# print("Precision:", precision)
# print("Recall:", recall)
# print("Specificity:", specificity)

X_new = X_new.drop(columns=[col for col in X_new.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)

accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():

    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new,y_train,X_new_test,y_test)

    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

# DT >>> Recall -  0.75

# XGB >> Recall -  0.77 >> الانسب عشان :
# “الموديل يتوقع إن فلان هيتخلف بس هو أصلًا مش هيتخلف” = False Positive
# مستعد أضحّي بشوية عملاء كويسين (FP)
# ميزيدش عندي عدد اللي هيتخلفوا عن السداد

# cat >> Recall -  0.74

"""# <div style="border-radius:0px; border:#3eb489 solid; padding: 15px; background-color: #ddefdd; font-size:100%; text-align:center">8. Hyperparameter Tuning</div>

> Add blockquote


"""

# الاصلي
# # Hyperparameter-tuning: Bayesian Optimization, bayes_opt
# def lgbm_clf_bo(num_leaves, max_depth, learning_rate, min_child_weight, subsample, colsample_bytree):
#     params_lgbm = {'objective': 'binary'}
#     params_lgbm['num_leaves'] = round((2**round(max_depth))*num_leaves)
#     params_lgbm['max_depth'] = round(max_depth)
#     params_lgbm['learning_rate'] = learning_rate
#     params_lgbm['min_child_weight'] = min_child_weight
#     params_lgbm['subsample'] = subsample
#     params_lgbm['colsample_bytree'] = colsample_bytree

#     scores = cross_val_score(LGBMClassifier(random_state=12, **params_lgbm),
#                              X_new, y_train, scoring='recall', cv=10).mean()
#     return scores

# # Set parameters distribution
# params_lgbm ={
#     'num_leaves':(0.5,0.9),
#     'max_depth': (3, 15),
#     'learning_rate': (0.005, 0.3),
#     'min_child_weight':(1e-6, 1e-1),
#     'subsample':(0.5, 1),
#     'colsample_bytree':(0.5, 1)
# }

# # Run Bayesian Optimization
# lgbm_bo = BayesianOptimization(lgbm_clf_bo, params_lgbm)
# lgbm_bo.maximize(init_points=2, n_iter=20)

# Hyperparameter Tuning for XGBoost (Bayesian Optimization)

# from bayes_opt import BayesianOptimization
# from xgboost import XGBClassifier
# from sklearn.model_selection import StratifiedKFold, cross_val_score
# import numpy as np

# احسب نسبة عدم التوازن: scale_pos_weight ≈ (#negative / #positive)
pos = int(np.sum(y_train))
neg = len(y_train) - pos
base_spw = neg / max(1, pos)

def xgb_clf_bo(max_depth, learning_rate, subsample, colsample_bytree,
               min_child_weight, gamma, reg_lambda, reg_alpha,
               n_estimators, spw_mult):
    params = {
        "objective": "binary:logistic",
        "eval_metric": "logloss",        # القياس الداخلي للموديل؛ التقييم الخارجي بالـ recall عبر CV
        "tree_method": "hist",
        "n_jobs": -1,
        "random_state": 12,

        "max_depth": int(round(max_depth)),
        "learning_rate": learning_rate,
        "subsample": subsample,
        "colsample_bytree": colsample_bytree,
        "min_child_weight": max(1.0, min_child_weight),
        "gamma": gamma,
        "reg_lambda": reg_lambda,
        "reg_alpha": reg_alpha,
        "n_estimators": int(round(n_estimators)),
        "scale_pos_weight": base_spw * spw_mult
    }

    model = XGBClassifier(**params)
    # CV خفيف للتجريب الأولي؛ تقدّر تزوده لاحقًا
    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=12)
    score = cross_val_score(model, X_new, y_train, scoring="recall", cv=cv, n_jobs=-1).mean()
    return score

# حدود بحث واقعية
pbounds = {
    "max_depth": (3, 10),
    "learning_rate": (0.01, 0.2),
    "subsample": (0.6, 1.0),
    "colsample_bytree": (0.6, 1.0),
    "min_child_weight": (1.0, 50.0),
    "gamma": (0.0, 5.0),
    "reg_lambda": (0.0, 5.0),
    "reg_alpha": (0.0, 1.5),
    "n_estimators": (300, 1500),
    "spw_mult": (0.6, 1.6)  # نسمح بالتحريك حوالين النسبة الأساسية
}

xgb_bo = BayesianOptimization(f=xgb_clf_bo, pbounds=pbounds, random_state=12, verbose=2)
xgb_bo.maximize(init_points=3, n_iter=25)

# أفضل نتيجة (Recall) وأفضل بارامترز:
# xgb_bo.max

xgb_bo.max

# Best hyperparameters — XGBoost (مكافئ لخطوة LightGBM في الصورة)
import numpy as np

# نسبة عدم التوازن الأساسية لتحويل spw_mult إلى scale_pos_weight
pos = int(np.sum(y_train))
neg = len(y_train) - pos
base_spw = neg / max(1, pos)

best = xgb_bo.max['params'].copy()

best_xgb_params = {
    'max_depth'       : int(round(best['max_depth'])),
    'learning_rate'   : float(best['learning_rate']),
    'subsample'       : float(best['subsample']),
    'colsample_bytree': float(best['colsample_bytree']),
    'min_child_weight': max(1.0, float(best['min_child_weight'])),
    'gamma'           : float(best['gamma']),
    'reg_lambda'      : float(best['reg_lambda']),
    'reg_alpha'       : float(best['reg_alpha']),
    'n_estimators'    : int(round(best['n_estimators'])),
    'scale_pos_weight': base_spw * float(best['spw_mult']),
}

best_xgb_params  # يطبع القيم النهائية

# Feature Importance (Classification) — RandomForestClassifier
# الغرض = تفسير وترتيب الفيتشرز

rfc.fit(X_new, y_train)
feature_scores = pd.Series(rfc.feature_importances_, index=X_new.columns).sort_values(ascending=False)
feature_scores

# اعلي فيتشرز تأثير في النتايج
# loan_to_income_ratio	0.125562
# loan_percent_income	0.113448
# person_income	0.089625
# loan_int_rate	0.088775

# ===== Build best_xgb_params from xgb_bo.max =====
import numpy as np

assert 'xgb_bo' in globals(), "لازم xgb_bo يكون موجود (خليّة الـ BO متشغّلة)."
assert 'y_train' in globals(), "لازم y_train يكون موجود."

best = xgb_bo.max['params']

pos = int(np.sum(y_train))
neg = len(y_train) - pos
base_spw = neg / max(1, pos)

best_xgb_params = {
    'max_depth'       : int(round(best['max_depth'])),
    'learning_rate'   : float(best['learning_rate']),
    'subsample'       : float(best['subsample']),
    'colsample_bytree': float(best['colsample_bytree']),
    'min_child_weight': float(best['min_child_weight']),
    'gamma'           : float(best['gamma']),
    'reg_lambda'      : float(best['reg_lambda']),
    'reg_alpha'       : float(best['reg_alpha']),
    'n_estimators'    : int(round(best['n_estimators'])),
    'scale_pos_weight': base_spw * float(best['spw_mult']),
}

print("✅ best_xgb_params جاهزة.")
best_xgb_params

"""**Testing**"""

# ===== Group final features into a dictionary (auto from X_new) =====
import json
assert 'X_new' in globals(), "X_new لازم يكون موجود."

feat_cols = list(X_new.columns)
present = set(feat_cols)

# ترتيب منطقي للفئات
groups = {
    "درجة ائتمانية":        ["A","B","C","D","E","F","G"],
    "وضع سكن":             ["MORTGAGE","RENT","OWN","OTHER"],
    "غرض القرض":           ["DEBTCONSOLIDATION","EDUCATION","HOMEIMPROVEMENT","MEDICAL","PERSONAL","VENTURE"],
    "شريحة/باند":          ["high","high-middle","middle","low-middle","low"],
    "فئة عمرية":           ["20-25","26-35","36-45","46-55","56-65"],
    "حجم/باند":            ["small","medium","large","very large"],
    "ثنائي":               ["N","Y"],
}

grouped = {}
for k, cols in groups.items():
    subset = [c for c in cols if c in present]
    if subset:
        grouped[k] = subset

# أي أعمدة أخرى (عددية/مشتقة) تتجمع هنا تلقائيًا
others = [c for c in feat_cols if all(c not in cols for cols in groups.values())]
if others:
    grouped["خصائص رقمية/مشتقة"] = others

print(json.dumps(grouped, ensure_ascii=False, indent=2))

# ===== Bank-style Test with RAW-friendly display =====
import numpy as np, pandas as pd
from sklearn.utils.validation import check_is_fitted
from xgboost import XGBClassifier

assert all(v in globals() for v in ['X_new_test','y_test','X_new', 'best_xgb_params']), "لازم X_new, X_new_test, y_test, and best_xgb_params be available."

# 1) Select the best performing model (XGBoost) and fit it
_model = XGBClassifier(**best_xgb_params)
_model.fit(X_new, y_train) # Fit the model

# 2) اختار عيّنة
idx = 0  # ← غيّرها لتجربة عميل تاني
row_std = X_new_test.iloc[[idx]]
y_true = int(np.array(y_test)[idx])

# 3) تعريف المجموعات (لعرض الفئات كبشر)
groups = {
    "Grade":          ["A","B","C","D","E","F","G"],
    "Residence":      ["MORTGAGE","RENT","OWN","OTHER"],
    "Purpose":        ["DEBTCONSOLIDATION","EDUCATION","HOMEIMPROVEMENT","MEDICAL","PERSONAL","VENTURE"],
    "Age band":       ["20-25","26-35","36-45","46-55","56-65"],
    "Size band":      ["small","medium","large","very large"],
    "Binary flag":    ["Y","N"],
    "Band":           ["high","high-middle","middle","low-middle","low"],
}
def pick_onehot(r, cols):
    present = [c for c in cols if c in r.columns]
    if not present: return "(n/a)"
    vals = r[present].iloc[0].to_dict()
    best = max(present, key=lambda c: vals[c])
    return best if vals[best] > 0.5 else "(baseline/none)"

# 4) نحاول نجيب القيم الخام (RAW) تلقائيًا:
raw_numeric_cols = [
    "person_age","person_income","person_emp_length","loan_amnt","loan_int_rate",
    "loan_percent_income","cb_person_cred_hist_length","loan_to_income_ratio",
    "int_rate_to_loan_amt_ratio","loan_to_emp_length_ratio"
]

def looks_standardized(df, cols):
    s = df[cols].select_dtypes(include='number')
    if s.empty: return False
    mu = s.mean().abs().mean()
    sigma = s.std(ddof=0).mean()
    return (mu < 0.5) and (abs(sigma - 1) < 0.5)

def find_raw_df(index_label):
    cands = []
    for name, obj in globals().items():
        if isinstance(obj, pd.DataFrame) and all(c in obj.columns for c in raw_numeric_cols):
            if index_label in obj.index:
                cands.append((name, obj))
    # استبعد الداتا المقيّسة (زي X_new / X_new_test)
    for name, df in cands:
        try:
            if not looks_standardized(df, raw_numeric_cols):
                return df
        except Exception:
            pass
    return None

def inverse_with_scaler():
    # نحاول نلاقي StandardScaler متخزن
    scaler = None
    for obj in globals().values():
        if hasattr(obj, "mean_") and hasattr(obj, "scale_") and hasattr(obj, "feature_names_in_"):
            scaler = obj
            break
    if scaler is None: return None
    raw = {}
    for c in raw_numeric_cols:
        if c in row_std.columns and c in scaler.feature_names_in_:
            j = list(scaler.feature_names_in_).index(c)
            z = float(row_std[c].iloc[0])
            raw[c] = z * float(scaler.scale_[j]) + float(scaler.mean_[j])
    return raw if raw else None

index_label = row_std.index[0]
raw_df = find_raw_df(index_label)
raw_vals = None
if raw_df is not None:
    # سحب القيم الخام مباشرة
    raw_vals = {c: float(raw_df.loc[index_label, c]) for c in raw_numeric_cols if c in raw_df.columns}
else:
    # محاولة عكس القياس عبر StandardScaler لو متوفر
    raw_vals = inverse_with_scaler()

# 5) تنبؤ
def predict_score(model, X):
    if hasattr(model, "predict_proba"):
        return float(model.predict_proba(X)[:, -1][0])
    if hasattr(model, "decision_function"):
        s = float(model.decision_function(X)[0]);  return 1.0 / (1.0 + np.exp(-s))
    return float(model.predict(X)[0])

check_is_fitted(_model)
score = predict_score(_model, row_std)
pred  = int(score >= 0.5)
lbl   = {0:"its safe", 1:"High Risk"}[pred]
actual= {0:"its safe", 1:"High Risk"}[y_true]
ok    = "✅ Correct" if pred == y_true else "❌ Incorrect"

# 6) عرض منسّق
print(f"🏦 Test case idx: {idx}")
print("— Selected categories —")
for k, cols in groups.items():
    print(f"  {k}: {pick_onehot(row_std, cols)}")

print("\n— Customer values (RAW view) —")
if raw_vals:
    for k in raw_numeric_cols:
        if k in raw_vals:
            print(f"  {k}: {raw_vals[k]:,.2f}")
else:
    print("  (القيم الخام غير متاحة تلقائيًا؛ المعروض أدناه قيَم مُقاسة z-score)")
    for k in raw_numeric_cols:
        if k in row_std.columns:
            print(f"  {k} (z): {float(row_std[k].iloc[0]):.3f}")

print(f"\n🔮 Model: {lbl}  (score={score:.4f})")
print(f"📌 Actual: {actual}  (y_test={y_true})")
print(f"🧪 Evaluation: {ok}")

# Binary flag >>> هل عنده تعثّر سابق مسجّل؟
# Band >>> شدة مخاطرة

# القيم السالبه هي القيم بعد ما اتعملها >> Standardization

# ليه بنعمل Standardization للقيم “الطبيعية” زي العمر/الدخل/مبلغ القرض؟
# مثلًا الدخل ممكن يبقى من 2,000 لـ 200,000، بينما الفايدة من 5 لـ 25 >>
# لو سبتهم خام، خوارزميات بتعتمد على المسافة أو الإسقاط هتخلي الميزة الكبيرة في المدى (الدخل) تهيمن على القرار

# ===== Mini GUI (self-healing) — trains if model not fitted =====
import numpy as np, pandas as pd, ipywidgets as W
from IPython.display import display, clear_output
from sklearn.utils.validation import check_is_fitted
import joblib

# -------- helpers: data & model ----------
def _find_first(names):
    for n in names:
        if n in globals():
            return globals()[n]
    return None

def _get_training_data():
    # نفضّل X_new / y_train لو موجودين (نفس اللي اتدرّبت عليه النوتبوك)
    X = _find_first(['X_new','X'])
    y = _find_first(['y_train','y'])
    if X is None or y is None:
        raise AssertionError("مش لاقي بيانات تدريب (عايز X_new/y_train أو X/y). شغّل خلايا التحضير/التدريب الأول.")
    # لو NumPy حوله DataFrame عشان الأعمدة
    if not isinstance(X, pd.DataFrame):
        cols = getattr(_find_first(['X_new_test','X_test']), 'columns', None)
        X = pd.DataFrame(X, columns=cols if cols is not None else [f'f{i}' for i in range(X.shape[1])])
    return X, np.array(y)

def _ensure_fitted_model():
    # حاول تلاقي موديل جاهز
    for name in ['xgb_final','ensemble','lgb','cat','xgb','final_model','best_xgb_model']:
        if name in globals():
            m = globals()[name]
            try:
                check_is_fitted(m)
                return m, name, False  # جاهز
            except Exception:
                candidate_name = name
                break
    else:
        candidate_name = None

    # لو وصلنا هنا يبقى لسه مفيش موديل fitted — جرّب ندرب XGB سريعًا
    X_tr, y_tr = _get_training_data()
    from xgboost import XGBClassifier

    # لو عندنا best_xgb_params استخدمها، غير كده defaults خفيفة
    params = {
        'random_state': 12, 'n_jobs': -1, 'tree_method': 'hist',
        'eval_metric': 'logloss', 'use_label_encoder': False
    }
    if 'best_xgb_params' in globals():
        params.update(globals()['best_xgb_params'])
    else:
        params.update(dict(
            n_estimators=400, max_depth=3, learning_rate=0.1,
            subsample=0.8, colsample_bytree=0.8
        ))
        # لو عندك عدم توازن كبير ومتوفر y:
        pos = int(np.sum(y_tr)); neg = len(y_tr) - pos
        if pos > 0:
            params['scale_pos_weight'] = neg / max(1, pos)

    m = XGBClassifier(**params)
    m.fit(X_tr, y_tr)
    joblib.dump(m, '/content/models/xgb_model.pkl')
    globals()['xgb_final'] = m
    return m, 'xgb_final', True  # اتدرّب دلوقتي

def _feature_names_from_model_or_data(model):
    if hasattr(model, "feature_names_in_"):
        return list(model.feature_names_in_)
    if 'X_new' in globals() and isinstance(globals()['X_new'], pd.DataFrame):
        return list(globals()['X_new'].columns)
    if 'X_new_test' in globals() and isinstance(globals()['X_new_test'], pd.DataFrame):
        return list(globals()['X_new_test'].columns)
    raise AssertionError("مش لاقي أسماء الأعمدة. لازم X_new/X_new_test أو model.feature_names_in_.")

def _find_scaler():
    # محاولة إيجاد StandardScaler (اختياري)
    for obj in globals().values():
        if hasattr(obj, "mean_") and hasattr(obj, "scale_") and hasattr(obj, "feature_names_in_"):
            return obj
    return None

# -------- get model + feature names ----------
model, model_name, just_trained = _ensure_fitted_model()
feat_names = _feature_names_from_model_or_data(model)
scaler = _find_scaler()

# -------- categorical groups (one-hot) ----------
groups = {
    "Grade":          [c for c in ["A","B","C","D","E","F","G"] if c in feat_names],
    "Residence":      [c for c in ["MORTGAGE","RENT","OWN","OTHER"] if c in feat_names],
    "Purpose":        [c for c in ["DEBTCONSOLIDATION","EDUCATION","HOMEIMPROVEMENT","MEDICAL","PERSONAL","VENTURE"] if c in feat_names],
    "Age band":       [c for c in ["20-25","26-35","36-45","46-55","56-65"] if c in feat_names],
    "Size band":      [c for c in ["small","medium","large","very large"] if c in feat_names],
    "Binary flag":    [c for c in ["Y","N"] if c in feat_names],
    "Band":           [c for c in ["high","high-middle","middle","low-middle","low"] if c in feat_names],
}
groups = {k:v for k,v in groups.items() if v}  # شيل الفارغة

# -------- numeric inputs (RAW) ----------
numeric_raw = [
    ("person_age", "العُمر (سنة)", 30.0),
    ("person_income", "الدخل السنوي", 30000.0),
    ("person_emp_length", "مدة العمل (سنة)", 3.0),
    ("loan_amnt", "مبلغ القرض", 10000.0),
    ("loan_int_rate", "سعر الفائدة ٪", 12.0),
]
raw_numeric_cols = [
    "person_age","person_income","person_emp_length","loan_amnt",
    "loan_int_rate","loan_percent_income","cb_person_cred_hist_length",
    "loan_to_income_ratio","loan_to_emp_length_ratio","int_rate_to_loan_amt_ratio"
]
maybe_index_col = 'index' if 'index' in feat_names else None

# -------- widgets ----------
cat_widgets = {g: W.Dropdown(options=opts, value=opts[0], description=g+":") for g,opts in groups.items()}
num_widgets = {k: W.FloatText(value=default, description=label+":") for k,label,default in numeric_raw}
btn = W.Button(description="Predict", button_style="primary")
out = W.Output()

# -------- build row ----------
def build_feature_row():
    v = pd.DataFrame([0]*len(feat_names), index=feat_names).T

    # one-hot
    for g, w in cat_widgets.items():
        cols = groups[g]
        v.loc[:, cols] = 0
        v.at[v.index[0], w.value] = 1

    # raw values
    vals = {k: w.value for k, w in num_widgets.items()}
    # مشتقات
    denom_income = max(1.0, vals.get("person_income", 0.0))
    loan_pct = vals.get("loan_amnt", 0.0) / denom_income
    cred_hist_len = 5.0  # تقدير بسيط لو مفيش إدخال
    loan_to_emp = vals.get("loan_amnt", 0.0) / max(1.0, vals.get("person_emp_length", 0.0))
    int_to_loan = (vals.get("loan_int_rate", 0.0) / 100.0) / max(1.0, vals.get("loan_amnt", 0.0))

    raw_fill = {
        "person_age": vals.get("person_age", 0.0),
        "person_income": vals.get("person_income", 0.0),
        "person_emp_length": vals.get("person_emp_length", 0.0),
        "loan_amnt": vals.get("loan_amnt", 0.0),
        "loan_int_rate": vals.get("loan_int_rate", 0.0)/100.0,  # لو عمودك مُخزّن كنسبة عشرية
        "loan_percent_income": loan_pct,
        "cb_person_cred_hist_length": cred_hist_len,
        "loan_to_income_ratio": loan_pct,
        "loan_to_emp_length_ratio": loan_to_emp,
        "int_rate_to_loan_amt_ratio": int_to_loan,
    }
    for k,val in raw_fill.items():
        if k in v.columns:
            v.at[v.index[0], k] = val

    if maybe_index_col:
        v.at[v.index[0], maybe_index_col] = 0

    # scaler اختياري
    if scaler is not None:
        common = [c for c in getattr(scaler, "feature_names_in_", []) if c in v.columns]
        for c in common:
            j = list(scaler.feature_names_in_).index(c)
            m = float(scaler.mean_[j]); s = float(scaler.scale_[j]) or 1.0
            v[c] = (v[c] - m) / s

    return v, raw_fill, scaler is not None

def predict_score(m, X):
    if hasattr(m, "predict_proba"):
        return float(m.predict_proba(X)[:, -1][0])
    if hasattr(m, "decision_function"):
        z = float(m.decision_function(X)[0])
        return 1/(1+np.exp(-z))
    return float(m.predict(X)[0])

# -------- click handler ----------
def on_click(_):
    with out:
        clear_output()
        try:
            X_row, raw_shown, used_scaler = build_feature_row()
            score = predict_score(model, X_row)
            pred = int(score >= 0.5)
            label = {0:"its safe", 1:"High Risk"}[pred]
            print(f"🧠 Model: {model_name}   |   just_trained: {just_trained}   |   used_scaler: {used_scaler}")
            print(f"🔮 Prediction: {label}  (score={score:.4f})")
            print("\n— Entered RAW values —")
            for k, v in raw_shown.items():
                if k == "loan_int_rate":
                    print(f"  {k}: {v*100:.2f}%")
                else:
                    print(f"  {k}: {v:,.2f}")
        except Exception as e:
            print("⚠️ حدث خطأ:", e)

btn.on_click(on_click)

# -------- render ----------
left  = W.VBox(list(cat_widgets.values()))
right = W.VBox(list(num_widgets.values()))
ui = W.HBox([left, W.Label('   '), right, W.Label('   '), btn])
display(ui, out)

